### ISSUE TITLE
Request: Support for Meta Quest Pro

### ISSUE THREAD

**Issue by uzair-ashraf** [benaclejames/VRCFaceTracking#106]

**Comment by regzo2** [comment]
A Quest Pro module is being worked on, alongside an expansion with more parameters to support tracking #105. 

If you would like to test it out there is currently a temporary method for getting face tracking to work in the VRCFaceTracking Discord. Please note that the current approach is not intended for final use and is solely meant for testing at the moment. 

Every VRCFT supported avatar currently works with it but the expanded parameter support is still being worked on; only a very small handful of avatars currently use the expanded parameter set (which tracks a few extra lip shapes and eye brows).
