### ISSUE TITLE
Lags out Vrchat, Does not crash app or Vr

### ISSUE THREAD

**Issue by Whittz** [benaclejames/VRCFaceTracking#113]
Unfortunately I have no logs that show this.
As of right now I can recreate the issues just by using the facetracking app and joining a world for about 10 minutes. Not sure if vrchat's OSC pipeline changed?  Not hardware issue. using 12900k and 3090. face tracker camera works with all other Vr games like helios/chilloutvr. Used this app flawlessly until a month ago.

Does not crash VR; I close vrc and the facetracking app, open it all up again and its fixed for another 10 minutes.

**Comment by benaclejames** [comment]
Are you using the recommended SRanipal version 1.3.1.1? This is most likely an issue with Vive's software pipeline.

**Comment by Whittz** [comment]
it is not. I've used the 1.3.1.1 and the updated one.  Both causes lag. seems like I have no errors or problems through vive's software

**Comment by benaclejames** [comment]
The app is open source, please feel free to throw it in a debugger and prove me wrong. It's vive's sdk. 
Thanks

**Comment by dfgHiatus** [comment]
Does an app called `lipsyncnotification.exe` take up a lot of your GPU in the background?

**Comment by Whittz** [comment]
unfortunately I had little time and little knowledge of debugging it.  Switched over to an alternative did seem to fix the issue. I'll re upload the avitar for this app and check app usage. but there were times I barely saw gpu/cpu spikes when it happened, and sometimes it was spiking until I closed vrchat

**Comment by benaclejames** [comment]
Closing stale thread. Please feel free to re-open once you have the results back between the two apps
