### ISSUE TITLE
High GPU Usage

### ISSUE THREAD

**Issue by SaladOwO** [benaclejames/VRCFaceTracking#114]
When launching the face tracking program something called "lipsyncnotification.exe" takes up 98% of my gpu, which is a RTX 3080. Closing it has no affect on the program. What is the reason for this? I suspected a miner.

**Comment by dfgHiatus** [comment]
`lipsyncnotification.exe` is part of SRanipal, the eye and face tracking software VRCFaceTracking uses. It is known for not closing down properly once it is launched, you can just delete or rename the executable in your install folder. You can find it relative to SRanipal like in this photo 

![image](https://user-images.githubusercontent.com/51272212/207756329-f4ceabb2-7711-472d-9b31-e81481634000.png)

**Comment by SaladOwO** [comment]
I see. Thank you 👍
