### ISSUE TITLE
Enhance Logger functionality and stability.

### ISSUE THREAD

**Issue by regzo2** [benaclejames/VRCFaceTracking#121]
Currently the Logger is directly called by almost every aspect of VRCFT and it's modules and does not currently have any error handling meaning that it can crash the entire application and does not produce a log properly.

**Comment by benaclejames** [comment]
For sure, handling the errors would be ideal. I saw the try catch you added in #109 but I think we should be more graceful in how we handle any errors thrown, which would mean we'd likely want to find **why** errors would be thrown there first

**Comment by regzo2** [comment]
Added `feat/ui` branch here as it pretty much solves this issue! merging `feat/ui` will close this.

**Comment by benaclejames** [comment]
Complete in 5.0
