### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by Dog** [benaclejames/VRCFaceTracking#142]
https://github.com/benaclejames/VRCFaceTracking/blob/1596ff1d63cadff8067bb1617f2a9b913cbe26d0/VRCFaceTracking.Core/VRCFaceTracking.Core.csproj#L16

I believe you are supposed to only bring in the redist exe and not directly hard copy the redist dll, but I believe this should be  `%VCToolsRedistDir%\x64\Micorosft.VC143.CRT\` rather than be hardcoded.

**Comment by benaclejames** [comment]
Still working on this. Due to the somewhat poorly documented nature of the .appinstaller format, I'm still searching for a way to tell it to install the vcredistributeable dependencies during initial install
