### ISSUE TITLE
5.0.2.1 crashes immediately upon loading the quest pro module 

### ISSUE THREAD

**Issue by sgao2022** [benaclejames/VRCFaceTracking#153]

**Comment by Gameruler02** [comment]
same with the sranipal tracking module

**Comment by deadcxap** [comment]
Likewise, even after a clean install, the application terminates instantly. The window doesn't even appear.
Checked versions 5.0.2.2, 5.0.2.1, 5.0.2.0. The last one running is 5.0.1.1.
Tried deleting all modules, clearing application data.

**Comment by benaclejames** [comment]
Have you tried deleting the current install, then downloading 5.0.2.2 using the .msix in the latest release?

**Comment by AmaliaKalio** [comment]
> Likewise, even after a clean install, the application terminates instantly. The window doesn't even appear. Checked versions 5.0.2.2, 5.0.2.1, 5.0.2.0. The last one running is 5.0.1.1. Tried deleting all modules, clearing application data.

I believe this is the same as [Issue 152](https://github.com/benaclejames/VRCFaceTracking/issues/152)

**Comment by benaclejames** [comment]
Update 5.0.2.3 is now out. Same issue?

**Comment by sgao2022** [comment]
> 

It is resolved. Thank you and other contributors for the fix!
