### ISSUE TITLE
very bad bug

### ISSUE THREAD

**Issue by ghostie5** [benaclejames/VRCFaceTracking#168]
I have been using this software a lot, and i have been having a really bad bug as of today that isnt being fixed for me at all. my face tracker will not pick up anything but 0m/s the entire time im using it. but the catch is it is only on vrcft. it works on neos, and works with motion capture. but vrcft randomly wont pick it up. please fix this

**Comment by ghostie5** [comment]
> Does your issue also include your modules not loading at ALL, because I've been having the same issue on my end and I JUST got my face 

it loads, that would be a firmware issue I belive with srinepal. but mine is just the software glitching

**Comment by benaclejames** [comment]
Is this resolved?
