### ISSUE TITLE
Face tracking completely bricks itself for Vive Pro Eye

### ISSUE THREAD

**Issue by SakuroJason** [benaclejames/VRCFaceTracking#179]
Hey, my experience with VRC Face Tracking was very good even though it crashed a lot but now my lip tracker does some weird things every time I use the headset. It's different every time I use it but it never tracks my face like it used to. I bought a new lip tracker to see if that is the problem but if this problem presists it has to do with VRC Face Tracking.

Kind regards

Jason

**Comment by RantiMess** [comment]
Have you tried replacing the headset cable?

**Comment by SakuroJason** [comment]
Yes it didn’t helpOn Nov 25, 2023, at 3:34 PM, RantiMess ***@***.***> wrote:﻿
Have you tried replacing the headset cable?

**Comment by benaclejames** [comment]
Is this resolved? If you need any more debugging or help, I'd highly recommend asking in [the discord](https://discord,gg/vrcft) where people who may have had the same issues can help you.

**Comment by SakuroJason** [comment]
I visited a group instance on VRChat from VRCFaceTracking and a user told me to disable automatic calibration. I don’t understand why it turns itself on and breaks my face tracking but I rather have a reinitialize button so if a device disconnects and reconnects, I don’t have to restart the whole program. On Nov 30, 2023, at 12:47 AM, Ben Thomas ***@***.***> wrote:﻿
Is this resolved? If you need any more debugging or help, I'd highly recommend asking in the discord where people who may have had the same issues can help you.
