### ISSUE TITLE
sranipal click not running SRanipalInstaller_1.3.1.1

### ISSUE THREAD

**Issue by Yukimill** [benaclejames/VRCFaceTracking#189]
When click the SRanipal runtime icon, it does not appear that the icon is created in the lower right notification window.
Currently, using vive PRO & VIVE facial tracking
If you can, please give me answer that solution about error.
SRanipalInstaller_1.3.1.1

**Comment by benaclejames** [comment]
Unrelated to VRCFT. Best bet would be asking in the Discord but SRanipal is known to be very finnicky
