### ISSUE TITLE
VRCFT ceases to operate after some time in the new V62 Meta Update.

### ISSUE THREAD

**Issue by ThunderStorm159** [benaclejames/VRCFaceTracking#192]
VRCFT stops registering OSC Data after a few hours of playtime. The only fix I've seen is to fully restart the Meta Quest PC App and relaunch VRCFT with Steam VR. Then to proceed into VRC. If you'd look into this then it'd be greatly appreciated. 
An educated guess of mine is an issue with the App and the Quest Pro XR Module.

**Comment by benaclejames** [comment]
This issue appears out of scope for this repo. Depending on which module you're using, I'd recommend posting an issue in one of these repos instead :)

https://github.com/ykeara/LinkFT
https://github.com/alvr-org/VRCFT-ALVR
https://github.com/korejan/VRCFT-ALXR-Modules
https://github.com/regzo2/VRCFaceTracking-QuestProOpenXR
