### ISSUE TITLE
Location of application

### ISSUE THREAD

**Issue by MaxineMaxie** [benaclejames/VRCFaceTracking#203]
I have VRCFT connected to VRCOSC and wish to make VRCFT open when VRCOSC does, but in order to do that I need the directory of VRCFT's EXE, but I cannot find it. May I have a location / is there an alternative if there isn't an EXE but it wants the path?

**Comment by PanDamien26** [comment]
C:\Program Files\WindowsApps\96ba052f-0948-44d8-86c4-a0212e4ae047_5.1.1.0_x64__d7rcq4vxghz0r\VRCFaceTracking.exe

**Comment by MaxineMaxie** [comment]
Alright, thank you so much!
