### ISSUE TITLE
"Sending" doesn't work but "listening" does

### ISSUE THREAD

**Issue by SparkYouTube** [benaclejames/VRCFaceTracking#207]
I have a Quest Pro, using SteamLink
I promise you, I have done every tutorial on the internet and nothing has fixed this
Nothing works

Yes, I have developer mode on
Yes, face and eye tracking is on
Yes, I have reset the avatar, reset OSC, reset the config
Yes, I have tried avatars made by VRCFT for facial tracking test

The code constantly says 
[SteamLinkVRCFTModule] Information Exception A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

All the other strings of code is me trying different things, trying to make anything work

[VRCFaceTracking doesn't work.txt](https://github.com/benaclejames/VRCFaceTracking/files/15358986/VRCFaceTracking.doesn.t.work.txt)

**Comment by InconsolableCellist** [comment]
The error's coming from connection code in the SteamLinkVRCFTModule (https://github.com/ykeara/LinkFT) while attempting to connect to OSC. Did you also check the settings on "OSC Output Port" and similar, which you can see on the linked README.md?

**Comment by SparkYouTube** [comment]
Where is the OSC Output Port?

**Comment by InconsolableCellist** [comment]
![image](https://github.com/benaclejames/VRCFaceTracking/assets/23345188/70555aa1-eecd-4ca0-8685-46378b14da06)

**Comment by SparkYouTube** [comment]
Just saw it after deleting that message. I am small brain X3

**Comment by SparkYouTube** [comment]
You're a fucking genius
God bless you
