### ISSUE TITLE
face tracking stopped working suddenly

### ISSUE THREAD

**Issue by coffee812** [benaclejames/VRCFaceTracking#220]
i was playing vrc for about 3 hours and my face tracking was working fine, but suddenly my face won't move at all. not even controller gestures work on most my ft avis.
[VRCFaceTracking.txt-7_11_2024-6_36 PM.txt](https://github.com/user-attachments/files/16184356/VRCFaceTracking.txt-7_11_2024-6_36.PM.txt)
![Screenshot 2024-07-11 183737](https://github.com/user-attachments/assets/c023c627-5fda-4e1d-b41a-4cd0875b4a16)
ive tried uninstalling and resetting everything including osc and recalibrating my eye tracking etc.

**Comment by InconsolableCellist** [comment]
Please seek support in the Discord, the link for which you can find here: https://docs.vrcft.io/

See the FAQ and support threads too.
