### ISSUE TITLE
Runtime failed to provide system information

### ISSUE THREAD

**Issue by St78724** [benaclejames/VRCFaceTracking#223]
Already tried to reinstall app, meta software, checked that in the meta app runtime is set. What it cloud be? It did work...

![image](https://github.com/user-attachments/assets/7197fa00-f1f5-4003-b4fc-7a5898564cab)

**Comment by benaclejames** [comment]
This repository's issues page is intended for general support with the vrcfacetracking application. For more target support for specific hardware and modules, please seek assistance in [the discord](https://discord.gg/vrcft)
