### ISSUE TITLE
VRC osc parameters all reading 0

### ISSUE THREAD

**Issue by cursingsum9** [benaclejames/VRCFaceTracking#228]
After the most recent VRC update my Face and eye tracking wont work.
VRCFT is both receiving and sending out data, and there are no errors from any avatar i use besides there being 2 or so legacy parameters being detected.
I tried looking up my issue everywhere, but everything i tried didnt work. I even switch from virtual desktop to steam link to see if virtual desktop was a problem.
I tried to turn off and on setting, hardware, software. Across all programs and the headset.
If possible i need help troubleshooting this.

**Comment by InconsolableCellist** [comment]
Please seek support in the Discord, and refer to the FAQ and threads for some common troubleshooting steps. Discord link in: https://docs.vrcft.io/
