### ISSUE TITLE
vive facial tracker with vive pro eye 

### ISSUE THREAD

**Issue by mil00oo39** [benaclejames/VRCFaceTracking#229]
ive used this for a decent while now, ran into this problem before but it fixed itself, my vive facial tracker just isnt detected even tho its on and has a green light showing.
![Screenshot 2024-09-06 030619](https://github.com/user-attachments/assets/5ff621d5-7659-46fd-ac62-3bb0af72eaa2)
![Screenshot 2024-09-06 030553](https://github.com/user-attachments/assets/74bee01c-feb2-4e96-8219-5693b5cf9efd)

**Comment by benaclejames** [comment]
Likely faulty cable. Please troubleshoot hardware in [the discord](https://discord.gg/vrcft)
