### ISSUE TITLE
Add LeftEyeBlink/RightEyeBlink boolean parameters

### ISSUE THREAD

**Issue by NGenesis** [benaclejames/VRCFaceTracking#24]
It would be neat to have `LeftEyeBlink` and `RightEyeBlink` boolean parameters that indicate whether the eye is fully closed to allow for simple blink animations that use 1 parameter bit each instead of 8 as with the `LeftEyeLid` and `RightEyeLid` parameters.

**Comment by benaclejames** [comment]
This will be added in the next update. It will be named the same as the normal float params (`LeftEyeLid` and `RightEyeLid`) but will register true while someone is blinking beyond 0.85 and false when the eye is open.
