### ISSUE TITLE
Add boolean parameter about initialized

### ISSUE THREAD

**Issue by kazu0617** [benaclejames/VRCFaceTracking#29]
Hi. I try to use this mod and according setting, sometimes confuse to detect SRanipal is initialized or not.

i'm now trying to detect some geek way (existing param check and not zero), but also think if add boolean param to detect initialize is more confortable.

**Comment by benaclejames** [comment]
I don't think I'll be adding a bool parameter to check for module initialization any time soon, you can tell if things have successfully started in the MelonLoader console at the moment. That said, you could modify the source code and add this functionality yourself using ParamLib
