### ISSUE TITLE
Face tracking params sometimes default to 1 or -1

### ISSUE THREAD

**Issue by InsaneGrox** [benaclejames/VRCFaceTracking#30]
Sometimes when first joining a session... combined params default to 1 or -1 instead of 0... this can be fixed by quickly moving your face around a lot but is annoying to do.

**Comment by dfgHiatus** [comment]
I can also confirm this happens on the latest release. It appears to affect a random parameter on join, anyone else having this issue?

**Comment by benaclejames** [comment]
I am aware of the issue and the reasons behind it, just trying to finish up the UI before going back into the merger and fixing stuff up in there 😄

**Comment by benaclejames** [comment]
*Should* be fixed next update! Hopefully won't require any avatar modifications
