### ISSUE TITLE
finding working Avatars

### ISSUE THREAD

**Issue by Progamer75303** [benaclejames/VRCFaceTracking#31]
can someone please send me the names of some working avatars so i can search them in emm. i searched for working ones for so long and dident found one and im not very good in unity so i dont know how to make these avatars

**Comment by benaclejames** [comment]
Sorry for the late response on this one. If you're still looking for an example project, InsaneGrox made one and linked it here in this old thread: https://github.com/benaclejames/VRCFaceTracking/issues/13#issuecomment-832826240
