### ISSUE TITLE
VRChat Update

### ISSUE THREAD

**Issue by TakkinFaircrest** [benaclejames/VRCFaceTracking#34]
I believe the latest VRChat update that dropped a few hours ago broke Eye Tracking. Trying to get others to confirm.

**Comment by benaclejames** [comment]
Yup, it broke all the param setting functionality. Working on a fix today

**Comment by benaclejames** [comment]
Fixed!

**Comment by InsaneGrox** [comment]
[MelonLoader_21-06-04_22-31-31.765.log](https://github.com/benaclejames/VRCFaceTracking/files/6601916/MelonLoader_21-06-04_22-31-31.765.log)
nope... sorry ben

**Comment by benaclejames** [comment]
I cri... Game updated less than a day after I update the mod. Latest release should be good to redownload. I updated the dll in there
