### ISSUE TITLE
Pupil Dilation resets to 0 when eyes close

### ISSUE THREAD

**Issue by InsaneGrox** [benaclejames/VRCFaceTracking#39]
This wouldn't be a problem if it wasn't for how VRC interpolates parameters over the network... the smoothing causes the pupils on avatars with pupil dilation to shrink really tiny when you blink in a very un-natural way.

**Comment by benaclejames** [comment]
The pupil diameter checks by vive are implemented and will probably stay untouched. I would reccomend using a transition to transition out of the blend tree when the eyelids close beyond an arbritrary point
