### ISSUE TITLE
[SRanipal] Use callbacks instead of GetEyeData

### ISSUE THREAD

**Issue by MoePus** [benaclejames/VRCFaceTracking#41]
doc:
[vive-eye-tracking-120hz](https://github.com/corycorvus/corycorvus.github.io/blob/3e3791e71961471d230ca1fe70d4aec7a2e99a9c/docs/vr-notes/vive-eye-tracking-120hz.md)

callbacks obviously reduce costs in game thread (in a plugin for another game)
...and how can i build this project?

**Comment by benaclejames** [comment]
The SRanipal data is collected and processed in a thread already, though I'll look into using the callback and see if it provides any performance benefit. To build you'll need the assemblies generated by unhollower

**Comment by benaclejames** [comment]
Implemented in next update
