### ISSUE TITLE
Only One eye moves

### ISSUE THREAD

**Issue by LazyNachos** [benaclejames/VRCFaceTracking#49]
Been following the guide and have blink working left and right no problem however I have issues with movement. I setup Left eye animations and tested them out and they work on their own however once I setup the Right eye the way the guide tells me only the right eye will move the left eye just sits still once I delete the blend type for the right eye the left eye tracks again. I've tried combining animations and making both eyes move at the same time in the same blend type but again the left eye just sits still while the right eye moves. I have no idea how to get this to work with both eyes

**Comment by regzo2** [comment]
Here is a bit of a hack I did to use to get both eyes to animate together; I'm assuming you are using two separate animation layers for each eye, and are trying to animate each eye bone (this issue won't arise if you use blendshape based eye movement). Set one of the eye movement layers to "1" in the Weight setting under the layer options (the cog), and set the other eye to ".5" in the Weight setting. This will get both eyes to animate, but will result them going half the distance you set the animations up to do. You will have to edit your animations to have double the rotation. If you use the Animator left/right eye properties to create animations, this will be very easy to do, but if you used something like Blender to create the animations then it may be a hassle.

That is currently how I work around the issue myself until I can find a better way. I partly think it is the way that Unity handles bone transforms that is to blame.

That will solve your issue, but you will have to edit your animations to compensate. I hope someone else can chime in and give a more proper resolution.
