### ISSUE TITLE
Face tracking stopped working or is my face tracker broken?

### ISSUE THREAD

**Issue by NamBo77** [benaclejames/VRCFaceTracking#52]
Hi I just booted up vrchat today and everything seemed fine but my avatar wasnt moving with my face movement so I checked the camera preview and it looked wierd, I was wondering if this has been seen before here or if my face tracker is just broken already. The green light on the side goes on and the red light next to the cameras goes on but it just doesnt track my face and the preview is the still image as shown in the image attached below. Sorry if this doesn't have anything to do with the mod but I can't find any other way to see if its on my end or not.
![face tracking preview](https://user-images.githubusercontent.com/82125345/140632155-532d42f5-0888-409b-b9ff-ae2f1bd41354.png)

**Comment by benaclejames** [comment]
Oof, that looks like a hardware fault! Not sure which part of your hardware has broken, but I'd contact Vive and ask for an RMA

**Comment by NamBo77** [comment]
> Oof, that looks like a hardware fault! Not sure which part of your hardware has broken, but I'd contact Vive and ask for an RMA

This is really wierd, I tried launching neosvr and it looked fine and then I tried booting up vrchat again and it just works again. I did try restarting my pc and reinstalling the mod but for some reason booting up neos just fixed it. 🤷‍♂️. Sorry for the inconvinience.
