### ISSUE TITLE
Support the HP G2 Reverb Omnicept

### ISSUE THREAD

**Issue by imagitama** [benaclejames/VRCFaceTracking#75]
# Idea

Support the HP G2 Reverb Omnicept VR headset's eye and lip tracking.

# Notes

Neos supports the eye tracking (https://github.com/Neos-Metaverse/NeosPublic/issues/2275) but not the lip sync as the API only exposes the raw camera capture not any data (or maybe it does but it isn't well documented).

There is a suggestion in Neos to make a generic API for eye/lip input that sounds perfect for this mod: https://github.com/Neos-Metaverse/NeosPublic/issues/1140

**Comment by Lewisvz** [comment]
I've reached out to HP for more information on the lip tracker.  I'm currently waiting for a response.

**Comment by Tazzy4311** [comment]
> I've reached out to HP for more information on the lip tracker. I'm currently waiting for a response.

if you can, I would love to know when you get updated on this'

**Comment by Lewisvz** [comment]
HP failed to respond it seems.  I might shoot them another email though.

**Comment by Tazzy4311** [comment]
> HP failed to respond it seems. I might shoot them another email though.

For sure, I'll keep you updated as well if I see anything pop up about it

**Comment by Tazzy4311** [comment]
> HP failed to respond it seems. I might shoot them another email though.

Nope haven't found anything on it, It seems I might have to change to a Vive pro Eye

**Comment by MilchZocker** [comment]
Im a bit late on that but i received a response from HP a while ago(3-4 months ago), but thats where the good news ends sadly:

![header image](https://cdn.discordapp.com/attachments/693953565437460510/974580239348928573/1652428378962.jpg?size=4096)

**Comment by benaclejames** [comment]
A link to @200Tigersbloxed's external tracking module has now been added to the readme. This will likely be the go-to module for omnicept tracking in the future.

**Comment by SummerSigh** [comment]
https://www.youtube.com/watch?v=KQB8f4X2v6g&t=2s

Time to get the G2 some mouth-tracking baby!

**Comment by Lewisvz** [comment]
It's about time.  Hp really let us down.
