### ISSUE TITLE
SRanipal Eye Tracking active even with just the Facial Tracker

### ISSUE THREAD

**Issue by Chickenbreadlp** [benaclejames/VRCFaceTracking#80]
When someone uses the Vive Facial Tracker, the SRanipal Eye Tracking routine is still being called. Usually this is fine, but when a user uses the Facial Tracker with a VRCFT Module for Eye Tracking (like this one: [m3gagluk/VRCFTVarjoModule](https://github.com/m3gagluk/VRCFTVarjoModule)), then SRanipal will try to overwrite these Values, causing weird behavior on certain Parameters.
Looking at the code, the same seems to be true the other way around (using a Vive Pro Eye, but with an external Module for Facial Tracking).

Maybe the SRanipal Interface should only run the update routines of the parts that were actually initialized to prevent this issue from happening.

**Comment by benaclejames** [comment]
Is this fixed in the latest release?
