### ISSUE TITLE
App crashing when a subdirectory of the OSC folder lacks an "Avatars" folder

### ISSUE THREAD

**Issue by CamsAvis** [benaclejames/VRCFaceTracking#83]
Line 54 of "ConfigParser.cs" assumes that there will be a subfolder "Avatars" within every folder underneath the OSC directory - if a directory underneath the OSC main directory lacks an "Avatars" subfolder the program will throw an IO error and crash immediately

**Comment by regzo2** [comment]
I can't seem to replicate this issue. Tested by removing 'Avatar' subfolder under the user folder. VRChat OSC regenerates this folder before VRCFT can read the file. Only tried with one user account in the OSC folder. Could you specify what exactly you did to replicate this issue? Also should mention I'm testing this under the 'ui' branch. Thanks!

**Comment by CamsAvis** [comment]
@regzo2 sorry for the delayed response - the issue lies when you have another folder underneath the OSC folder. If this folder does not contain an `Avatars` folder, the app crashes on changing into a new avatar

![image](https://user-images.githubusercontent.com/75397200/163690426-3521ab45-a1b7-49b7-a346-44c24ee3fa6a.png)

**Comment by regzo2** [comment]
All righty, will look into it!
