### ISSUE TITLE
Droolon F1 passed calibration of Vive pro eye but not working with the eye tracking

### ISSUE THREAD

**Issue by MasterSiu** [benaclejames/VRCFaceTracking#87]
The Droolon F1 calibration using the Vive Pro Eye overlay in the steamVR dashboard. When loading the VRCfacetrack osc with "is vpe" removed, only blinking is working in the VRchat. Eye widening, eye squeeze, and eye tracking is not working. The Droolon drivers created some files inside the eye_camera_device folder inside SRanipal folder in Program Files when I run the Droolon driver setup. I have attached these files under this issue as google drive link.

https://drive.google.com/file/d/16a4xzKIDGViLQec4kzlEibaPQHfRTyFD/view?usp=sharing

**Comment by regzo2** [comment]
I worked with someone who has the Droolon F1 very recently, we've managed to get the Droolon F1 fully functional with a modified version of VRCFaceTracking. Looks like the way the F1 is initialized seems really flakey, causing some parameters to not load properly sometimes (like gaze). Will be working with them further to hopefully get the F1 to be in a usable state.

**Comment by regzo2** [comment]
Also they were using it with the Vive Cosmos Elite completely unmodified just to add, with no lip tracking at the moment

**Comment by benaclejames** [comment]
Removed the IsViveProEye check in latest update, hopefully this fixes your issue!
