### ISSUE TITLE
crashes upon start

### ISSUE THREAD

**Issue by guppyexpress** [benaclejames/VRCFaceTracking#89]
running the EXE causes a crash on the program the second it starts
![image](https://user-images.githubusercontent.com/71186470/167976220-b28363fe-5154-490f-9d6f-aec0ae1c9930.png)

**Comment by benaclejames** [comment]
Weird, does this happen on [bleeding edge](https://github.com/benaclejames/VRCFaceTracking/actions/runs/2241746658)?

**Comment by guppyexpress** [comment]
yep, happens on it still too :/

**Comment by Louka3000** [comment]
Same happens to me whenever I put the pimax module in the customlibs folder.

**Comment by benaclejames** [comment]
Can someone pass me a link to this module please?

**Comment by benaclejames** [comment]
Ah, looks like Dazbme is still using the old custom tracking lib framework, I'll PR a fix and post another DLL here soon
