### ISSUE TITLE
Request: Parameter Prefixes (e.g. `PuffSuck` -> `VRCFT/PuffSuck`)

### ISSUE THREAD

**Issue by rrazgriz** [benaclejames/VRCFaceTracking#97]
### Problem

Face tracking often adds a significant number of parameters to deal with, which can make later manual editing of controllers unwieldy.

### Solution

Add Optional detection and addressing of VRCFT parameters that are prefixed.

Ideally, this would support any user-specified prefix, simply identifying VRCFT parameters at the end of the parameter name. However, a fixed prefix (like `FaceTracking/`, `FT/`, or `VRCFT/`) would still solve the issue, albeit with less flexibility.

### Details

Parameters in the format `Name/Of/Parameter` will be organized by Unity in dropdowns (see video). Synced parameters with names in this format also organize themselves into dropdowns in VRChat menu and parameter objects.

Synced parameters can be addressed by OSC in the same way as any other parameter: `/avatar/parameters/Name/Of/Parameter`, so it's supported natively.

This would be a great add for organization and efforts to create cleaner controllers, and remains capable of addressing parameters with no prefix, ensuring backward compatibility.

https://user-images.githubusercontent.com/47901762/182968719-37c83559-c41f-4cb6-a344-1bc28f01c181.mp4

**Comment by regzo2** [comment]
Implemented in https://github.com/benaclejames/VRCFaceTracking/pull/109/commits/554d0060ef4f4f830f106c2ae61726dadd1e57d7, will close this request as complete on PR pull!
