### ISSUE TITLE
"Slideshow" effect to other users

### ISSUE THREAD

**Issue by TheReflectingVoid** [benaclejames/VRCFaceTracking#98]
When I use Facetracking with this and the latest Vive software in VRChat people state that while I see a smooth facetracking animation they are seeing a laggy, delayed or slideshow effect.  Is there a way to mitigate this?

**Comment by regzo2** [comment]
This is an issue with VRChat for the most part, however you can fix this by smoothing the parameters in the animator. I made a tool to do this and you can set how smooth each parameter feels locally and for other people. There are also other tools that have smoothing included as well, and I'll list them below:

OSCmooth Tool (convert existing animator to be smoothed): https://github.com/regzo2/OSCmooth
VRCFT Generator (creates a compact face tracking setup with smoothing included): https://github.com/rrazgriz/VRCFTGenerator

Let me know if this answers your question!
